[package]
name = "battery-status"
version = "2.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dark-light = "2.0.0"
iced = { version = "0.13.1", features = ["tokio"] }
starship-battery = "0.10.0"
